# Generated by Django 6.0.1 on 2026-01-27 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('benefits', '0007_member_cover_end_date_member_cover_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=100)),
                ('status', models.CharField(default='registered', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benefits.member')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benefits.policy')),
            ],
        ),
    ]
