# Generated by Django 6.0.1 on 2026-02-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('under_process', 'Under Process'), ('settled', 'Settled'), ('approved', 'Approved'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('repudiated', 'Repudiated')], default='registered', max_length=50),
        ),
    ]
