# Generated by Django 6.0.1 on 2026-01-22 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0003_member_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_premium_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('premium_used', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_buffer', to='benefits.policy')),
            ],
        ),
    ]
