# Generated by Django 6.0.1 on 2026-01-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0004_premiumbuffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
