# Generated by Django 6.0.1 on 2026-01-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0005_member_employee_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='employee_code',
            field=models.CharField(default='LEGACY', max_length=50),
            preserve_default=False,
        ),
    ]
