# Generated by Django 6.0.1 on 2026-01-27 17:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0006_alter_member_employee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cover_end_date',
            field=models.DateField(default=datetime.date(2026, 1, 27)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='cover_start_date',
            field=models.DateField(default=datetime.date(2026, 1, 27)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='premium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='PremiumRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=50)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('sum_insured', models.IntegerField()),
                ('annual_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benefits.product')),
            ],
        ),
    ]
