# Generated by Django 6.0.1 on 2026-01-28 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmessage',
            name='status',
        ),
    ]
